---
# tasks file for roles/database
- name: Run database
  docker_container:
    name: pgsql
    image: younesabo/pgsql
    env:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: usr
      POSTGRES_DB: db
    state: started