all :
    vars :
        ansible_user : centos
        ansible_ssh_private_key_file : /home/younes/TP1_Devops/ansible/inventories/id_rsa
    children :
        prod :
            hosts : younes.abouchi.takima.cloud
